create table users
(
    username   varchar(255) primary key,
    password   varchar(255),
    first_name varchar(255),
    last_name  varchar(255)
);

create table tasks
(
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    assigned_to     varchar(255) references users,
    due_date        date,
    ongoing_tasks   varchar(255),
    task_priority   varchar(255)
);

create table task_attached_files
(
    task_id         bigint references tasks on delete cascade,
    attached_files  varchar(255),
    primary key (task_id, attached_files)
);

create table task_linked_items
(
    task_id         bigint references tasks on delete cascade,
    linked_items    varchar(255),
    primary key (task_id, linked_items)
);

create table workspaces
(
    id          bigint generated by default as identity primary key,
    name        varchar(255),
    description varchar(4000)
);

create table workspace_tasks
(
    workspace_id bigint references workspaces on delete cascade,
    task_id      bigint references tasks on delete cascade,
    primary key (workspace_id, task_id)
);

create table workspace_users
(
    workspace_id bigint references workspaces on delete cascade,
    user_username varchar(255) references users on delete cascade,
    primary key (workspace_id, user_username)
);
