apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: chatmed
  labels:
    app: backend-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-app
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 500
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-pod
          image: evgenijasotiroska24/kiiiproekt-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: chatmedui-config
                  key: SERVER_ADDRESS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: chatmedui-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: chatmed
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: backend-app